openapi: 3.1.0
info:
  title: 3FC Core Write API
  version: 0.1.0
  description: |
    Authenticated core write routes for league/season/session/game creation.
servers:
  - url: https://qa-api.3fc.football
    description: QA
  - url: https://api.3fc.football
    description: Production
paths:
  /v1/leagues:
    post:
      summary: Create league
      operationId: createLeague
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLeagueRequest"
      responses:
        "201":
          description: League created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/League"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "409":
          $ref: "#/components/responses/IdempotencyConflict"
  /v1/leagues/{leagueId}/seasons:
    post:
      summary: Create season
      operationId: createSeason
      parameters:
        - name: leagueId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSeasonRequest"
      responses:
        "201":
          description: Season created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Season"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/IdempotencyConflict"
  /v1/seasons/{seasonId}/sessions:
    post:
      summary: Create session
      operationId: createSession
      parameters:
        - name: seasonId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionRequest"
      responses:
        "201":
          description: Session created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/IdempotencyConflict"
  /v1/sessions/{sessionId}/games:
    post:
      summary: Create game
      operationId: createGame
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGameRequest"
      responses:
        "201":
          description: Game created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/IdempotencyConflict"
components:
  parameters:
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
        minLength: 1
        maxLength: 128
      description: Optional idempotency key for replay-safe writes.
  responses:
    BadRequest:
      description: Request body or headers failed validation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Unauthorized:
      description: Missing or invalid session
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Forbidden:
      description: Caller does not have required ACL permissions
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Referenced parent entity not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    IdempotencyConflict:
      description: Idempotency key was reused with a different request payload
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  schemas:
    CreateLeagueRequest:
      type: object
      additionalProperties: false
      required:
        - leagueId
        - name
      properties:
        leagueId:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        slug:
          type:
            - string
            - "null"
    CreateSeasonRequest:
      type: object
      additionalProperties: false
      required:
        - seasonId
        - name
      properties:
        seasonId:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        slug:
          type:
            - string
            - "null"
        startsOn:
          type:
            - string
            - "null"
        endsOn:
          type:
            - string
            - "null"
    CreateSessionRequest:
      type: object
      additionalProperties: false
      required:
        - sessionId
        - sessionDate
      properties:
        sessionId:
          type: string
          minLength: 1
        sessionDate:
          type: string
          minLength: 1
    CreateGameRequest:
      type: object
      additionalProperties: false
      required:
        - gameId
        - gameStartTs
      properties:
        gameId:
          type: string
          minLength: 1
        gameStartTs:
          type: string
          minLength: 1
        status:
          type: string
          enum:
            - scheduled
            - live
            - finished
    League:
      type: object
      required:
        - leagueId
        - name
        - slug
        - createdByUserId
        - createdAt
        - updatedAt
      properties:
        leagueId:
          type: string
        name:
          type: string
        slug:
          type:
            - string
            - "null"
        createdByUserId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Season:
      type: object
      required:
        - leagueId
        - seasonId
        - name
        - slug
        - startsOn
        - endsOn
        - createdAt
        - updatedAt
      properties:
        leagueId:
          type: string
        seasonId:
          type: string
        name:
          type: string
        slug:
          type:
            - string
            - "null"
        startsOn:
          type:
            - string
            - "null"
        endsOn:
          type:
            - string
            - "null"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Session:
      type: object
      required:
        - seasonId
        - sessionId
        - sessionDate
        - createdAt
        - updatedAt
      properties:
        seasonId:
          type: string
        sessionId:
          type: string
        sessionDate:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Game:
      type: object
      required:
        - gameId
        - leagueId
        - seasonId
        - sessionId
        - status
        - gameStartTs
        - createdAt
        - updatedAt
      properties:
        gameId:
          type: string
        leagueId:
          type: string
        seasonId:
          type: string
        sessionId:
          type: string
        status:
          type: string
          enum:
            - scheduled
            - live
            - finished
        gameStartTs:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      additionalProperties: true
      required:
        - error
      properties:
        error:
          type: string
        message:
          type: string
